all:
  vars:
    ansible_ssh_user: userb3
    cert_admin_email: marcus.neves@alsofer.com
  children:
    kubernetes:
      children: 
        masters:
          vars:
            linkerd_url: linkerd.k8s.intranet.montreal.com.br
          hosts:
            10.2.19.11:
            10.2.19.21
        nodes:
          hosts:
            10.2.19.12:
            10.2.19.22: